 /*
 * Copyright 2013 Martin Schreiber, Arash Bakhtiari
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

* Install & Run
** MAC Cluster:
** TOEDI Cluster
To compile the code on the Toedi Cray Cluster 
execute the following commands:
- $ module swap PrgEnv-cray PrgEnv-intel
- $ module load scons
- $ module load cudatoolkit
- $ scons --compiler=CC --mode={release|debug}

* Benchmark
TODO:


* LEGACY README

This directory contains a lattice Boltzmann method based driven cavity simulation with the A-A pattern.

Please visit http://www.martin-schreiber.info/diplomathesis.html for further information


Information about the directories:


data/cl_programs:	The opencl kernel programs
doc:				Documentation directory for doxygen
benchmarks/gnuplot:	Scripts and output directory for different benchmarks
data/images:		Image directory
src/:				Source folder
src/include:		Genearl include directory for the OpenGL 3 header file since this is not shipped with the current NVIDIA drivers
src/lib:			General libraries and utilities which usually do not depend on things like visualization or simulation
src/libcl:			OpenCL object oriented abstraction classes
src/libmath:		Math utility classes
